use_frameworks!

platform :ios, '11.0'

target 'RCSceneGameRoom_Example' do
  use_frameworks!
  pod 'RCSceneGameRoom', :path => '../'

  target 'RCSceneGameRoom_Tests' do
    inherit! :search_paths

    
  end
end
